language: java
jdk:
  - oraclejdk8
sudo: required
dist: trusty
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - export PATH=$HOME/.yarn/bin:$PATH
  #- rm -rf node_modules
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
  - sh -e /etc/init.d/xvfb start
install: gradle/installViaTravis.sh

jobs:
  include:
    - stage: tests
      name: run tests for deck
      script: gradle/buildViaTravis.sh
    - name: build the all module libs
      script: gradle/buildModules.sh

before_cache: gradle/prepCaches.sh
cache:
  directories:
    - $HOME/.gradle
    - node_modules
env:
  global:
    - secure: B3KkWCFv2I+fqAIL6NcfK6is+CrTTsrhTOxRjD1DwnqduxfGOjrS+3qVD8NfIGx7O3MsCk0CCnz1xqiOFrLERf8elhCuEuVjumSpt9VZwpsd+hKmNQeuVoFABB1hlZrHdr2rDH17KVT+TgWNTDSt9Mk3cvRAq+j2BxOHxZXDi59PiVaRGiiM4/aEBtF0/zWfusGIHRGsouGENJU1Zi6xyt0MChx3SCDL2p5qMduGWYsnnUy4BnHMPBi+pF30mjKTI+9JVrecFRuSFezh+MEE67ZiJNw/6bAsZ35sPrd/ECEiELwiEUekpNyXu9/1AxlzaKzrHDnijuZJoEvIaKV8WYwjGjhljF0QNuWGkaKQUcIs4bOKxAY2E62/ZjDbb5J8P3V7k5FD/RHdbVva0A0g7twUNR1vJIk8DFFdY4zqgCRxCyKlQKTdTjk/tV/PjxX5MAQT5J6/OgNLohA8tLRN72xvnDd9XFaKV9RJW23a4xGNUBH24wn1Od11lqR2ZU6/oejXqSojee8IgsjcCXypwW0ZS6OAOjybjxlt/n0av4MKnLFaEmUvxRP26gGJ1H8nfgNCnsLAH9UD1y1XT3VmU7g32cv8AUKyxhh/IgBG2qiqjVNaWvqK8YrepnR0Rbti5AnUiLz8QwipWW3g9DUffUWR98Ubjzs3kMzorbRB7rM=
    - secure: Sy0YuNrTfgkLKvCDWDKKKrc/C1pIRz4+iD9sIA67VrhkLhyWr/+tXd5Rn49PfyY0DrbyFygQ5rrtuCQOCmKluZwkvroqTJ9n1Nu2RcoapsFoHMW5hiUaBUHVjiL1CbbOdE05uvKGxn27y/HUMdfX9w9sGQ5wlT4yRjMtt/ajtWJwy696UJwJnZRONJerJb+w4tWwafIqKdiHLpp/1P8ziilVD3lwgSLmCY8ljmvmz+2GPY/NkC4Mkk7BUgSPcWu0uKXJxGYkSnsg9jCeopzmHRT8fzEGzBYw52rf92XRMr9ghbVVGeyUXEpTW8JOQTnKmnQM0oq2/yh46pWMOdShyXp+Ys794Oo1UiLhJQUkJXc60S7ByvjA1FZH2d2m07Z9la+RzUBzM0QIJ/2Q4ZS+5YUH3hXpiAUg129/EB4+M7GzsjIthkdLpkwRMhAPJns4E2yarf3l0frN7vecC9qhB7ShdBcBAwg3rc5Mx6lAtoOis5iqMENV4HnOPVxveitZLeiMcAjU664P7D/xCx7AOxiHbiifRbAqXaYVBYjQae0pmnPHulkFqw6NPZSUdZ0PaqmAxM8DRqHsCzTgRjrBt4bgcOWt0S5skJ+Thul6dtl96dwURXQlxBEsuz6dzZ3voZGPZTqzhyQVT0yWJreyQ3oKDEn3Ip/0AwubzjnslHk=
